// <auto-generated />
using CatalogAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CatalogAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230903192545_InitialMigrarion")]
    partial class InitialMigrarion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CatalogAPI.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("Feminine")
                        .HasColumnType("boolean");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Zara",
                            Feminine = false,
                            Image = "product-1.jpg",
                            Name = "Camisa Larga com Bolsos",
                            Price = 70m,
                            Size = "M"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Zara",
                            Feminine = true,
                            Image = "product-2.jpg",
                            Name = "Casaco Reto com Lã",
                            Price = 85m,
                            Size = "M"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Zara",
                            Feminine = false,
                            Image = "product-3.jpg",
                            Name = "Jaqueta com Efeito Camurça",
                            Price = 60m,
                            Size = "M"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Zara",
                            Feminine = false,
                            Image = "product-4.jpg",
                            Name = "Sobretudo em Mescla de Lã",
                            Price = 160m,
                            Size = "M"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Zara",
                            Feminine = false,
                            Image = "product-5.jpg",
                            Name = "Camisa Larga Acolchoada de Veludo Cotelê",
                            Price = 110m,
                            Size = "M"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Zara",
                            Feminine = true,
                            Image = "product-6.jpg",
                            Name = "Casaco de Lã com Botões",
                            Price = 170m,
                            Size = "M"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Zara",
                            Feminine = true,
                            Image = "product-7.jpg",
                            Name = "Casaco com Botões",
                            Price = 75m,
                            Size = "M"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Zara",
                            Feminine = true,
                            Image = "product-8.jpg",
                            Name = "Colete Comprido com Cinto",
                            Price = 88m,
                            Size = "M"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
